### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by fengyunzaidushi** [AIFSH/MyHeyGen#1]
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/inference.py", line 16, in <module>
    from third_part.GPEN.gpen_face_enhancer import FaceEnhancement
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 8, in <module>
    from face_model.face_gan import FaceGAN
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/face_gan.py", line 13, in <module>
    from face_model.gpen_model import FullGenerator
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/gpen_model.py", line 16, in <module>
    from face_model.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_act.py", line 13, in <module>
    fused = load(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_89'
[2/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp -o fused_bias_act.o 
In file included from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:4,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/c10/core/Device.h:5,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:1:
/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp: In function ‘at::Tensor fused_bias_act(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float, float)’:
/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:7:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    7 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                         ^
/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:13:5: note: in expansion of macro ‘CHECK_CUDA’
   13 |     CHECK_CUDA(input);
      |     ^~~~~~~~~~
In file included from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:1:
/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:4,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/c10/core/Device.h:5,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:1:
/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:7:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    7 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                         ^
/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:14:5: note: in expansion of macro ‘CHECK_CUDA’
   14 |     CHECK_CUDA(bias);
      |     ^~~~~~~~~~
In file included from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act.cpp:1:
/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
ninja: build stopped: subcommand failed.

(myheygen) ubuntu@ubuntu:/mnt/sda/github/11yue/MyHeyGen$ bash dubbing.sh 
output_language:zh-cn
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../home/ubuntu/.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu118. Bad things might happen unless you revert torch to 1.x.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../home/ubuntu/.cache/torch/pyannote/models--pyannote--segmentation/snapshots/c4c8ceafcbb3a7a280c2d357aee9fbc9b0be7f9b/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu118. Bad things might happen unless you revert torch to 1.x.
default speaker num is 1, you can change SPEAKER_NUM in config.json to enable scene_processor
onnx load done
[Step 1] Reading the video, getting audio (voice + noise), as well as the text of the voice
Processing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.80s/it]
Detected language: en (0.95) in first 30s of audio...
When speaker num is 1, step 2,3 skipped!!!
[Step 4] Merging voices, translating speech, cloning voices
test/zimu.txt
cuda memeroy:62914560
 > Using model: xtts
TTS model tts_models/multilingual/multi-dataset/xtts_v2 Loaded,you may need CTRL+C to continue
 I kept Israel safe.   en   zh
{
    "from": "en",
    "to": "zh",
    "trans_result": [
        {
            "src": "I kept Israel safe.",
            "dst": "我保护了以色列的安全。"
        }
    ]
}
You can edit it in config.json HUMAN_TRANS as 1 to enable human trans mode
final translate result:我保护了以色列的安全。
 > Text splitted to sentences.
['我保护了以色列的安全。']
 > Processing time: 0.7577335834503174
 > Real-time factor: 0.27300695286077614
[Step 5] Creating final speech audio
[Step 6] Using video-retalking merge speech voice and video, creating output
cuda memeroy:62914560
Traceback (most recent call last):
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/inference.py", line 16, in <module>
    from third_part.GPEN.gpen_face_enhancer import FaceEnhancement
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 8, in <module>
    from face_model.face_gan import FaceGAN
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/face_gan.py", line 13, in <module>
    from face_model.gpen_model import FullGenerator
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/gpen_model.py", line 16, in <module>
    from face_model.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_act.py", line 13, in <module>
    fused = load(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_89'
ninja: build stopped: subcommand failed.
```

**Comment by AIFSH** [comment]
try this：
```
pip uninstall ninjia
pip install ninja==1.10.2.3
```

**Comment by fengyunzaidushi** [comment]
谢谢！ 我发现问题是cuda和cudnn的版本，重新安装了cuda11.8+cudnn8.9.5的版本可以了。原来是cuda11.7+cudnn 8.8.0
