### ISSUE TITLE
shape_predictor_68_face_landmarks.dat在哪儿下

### ISSUE THREAD

**Issue by congling** [AIFSH/MyHeyGen#14]
在ubuntu下执行这个指令（PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python translate.py /tmp/test2.mp4 en -o /tmp/out.test.mp4） ，发现以下问题：

[Info] Using cuda for inference.
face: /tmp/test2.mp4
[Step 0] Number of frames available for inference: 900
Traceback (most recent call last):
  File "/home/congling/MyHeyGen/video-retalking/inference.py", line 368, in <module>
    main()
  File "/home/congling/MyHeyGen/video-retalking/inference.py", line 63, in main
    croper = Croper('checkpoints/shape_predictor_68_face_landmarks.dat')
  File "/home/congling/MyHeyGen/video-retalking/utils/ffhq_preprocess.py", line 37, in __init__
    self.predictor = dlib.shape_predictor(path_of_lm)
RuntimeError: Unable to open checkpoints/shape_predictor_68_face_landmarks.dat

我下载了checkpoints，的确没有这个文件

**Comment by congling** [comment]
哦，文件没下完，sorry
