### ISSUE TITLE
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

### ISSUE THREAD

**Issue by fengyunzaidushi** [AIFSH/MyHeyGen#2]
```
(myheygen) ubuntu@ubuntu:/mnt/sda/github/11yue/MyHeyGen$ bash dubbing.sh 
output_language:zh-cn
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../home/ubuntu/.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu118. Bad things might happen unless you revert torch to 1.x.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../home/ubuntu/.cache/torch/pyannote/models--pyannote--segmentation/snapshots/c4c8ceafcbb3a7a280c2d357aee9fbc9b0be7f9b/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu118. Bad things might happen unless you revert torch to 1.x.
default speaker num is 1, you can change SPEAKER_NUM in config.json to enable scene_processor
onnx load done
[Step 1] Reading the video, getting audio (voice + noise), as well as the text of the voice
Processing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  4.00s/it]
Detected language: en (0.95) in first 30s of audio...
When speaker num is 1, step 2,3 skipped!!!
[Step 4] Merging voices, translating speech, cloning voices
/mnt/sda/github/11yue/MyHeyGen/test/zimu.txt
cuda memeroy:62914560
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
TTS model tts_models/multilingual/multi-dataset/xtts_v2 Loaded,you may need CTRL+C to continue
 I kept Israel safe.   en   zh
{
    "from": "en",
    "to": "zh",
    "trans_result": [
        {
            "src": "I kept Israel safe.",
            "dst": "我保护了以色列的安全。"
        }
    ]
}
You can edit it in config.json HUMAN_TRANS as 1 to enable human trans mode
final translate result:我保护了以色列的安全。
 > Text splitted to sentences.
['我保护了以色列的安全。']
 > Processing time: 1.413506269454956
 > Real-time factor: 0.5292008496584111
[Step 5] Creating final speech audio
[Step 6] Using video-retalking merge speech voice and video, creating output
cuda memeroy:62914560
/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 57
[Step 1] Landmarks Extraction in Video.
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:09<00:00,  6.31it/s]
[Step 2] 3DMM Extraction In Video:: 100%|████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 93.72it/s]
using expression center
Load checkpoint from: checkpoints/DNet.pt
Load checkpoint from: checkpoints/LNet.pth
Load checkpoint from: checkpoints/ENet.pth
[Step 3] Stabilize the expression In Video:: 100%|███████████████████████████████████████████████████████████| 57/57 [00:02<00:00, 20.36it/s]
Traceback (most recent call last):
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/inference.py", line 360, in <module>
    main()
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/inference.py", line 189, in main
    mel = audio.melspectrogram(wav)
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/utils/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/utils/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/utils/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
```

**Comment by fengyunzaidushi** [comment]
根据这里的解释 [ https://github.com/Rudrabha/Wav2Lip/issues/471]( https://github.com/Rudrabha/Wav2Lip/issues/471) 降低版本 librosa 为0.8.0 ，结果又提示：tts 0.20.2 requires librosa==0.10.*, but you have librosa 0.8.0 which is incompatible.

**Comment by AIFSH** [comment]
> 根据这里的解释 [ https://github.com/Rudrabha/Wav2Lip/issues/471]( https://github.com/Rudrabha/Wav2Lip/issues/471) 降低版本 librosa 为0.8.0 ，结果又提示：tts 0.20.0 requires librosa==0.10.*, but you have librosa 0.8.0 which is incompatible.
> 
> 
> 

no matter
