### ISSUE TITLE
Cannot recognize 'zh-cn' in voice_cloner.py 无法识别 zh-cn

### ISSUE THREAD

**Issue by z-funfan** [AIFSH/MyHeyGen#22]
System: Ubuntu
Python: 3.10
TTS_MODEL:"tts_models/multilingual/multi-dataset/xtts_v2"
Seems like it cannot recognize 'zh-cn'
貌似无法识别‘zh-cn’

But after I checked https://github.com/coqui-ai/TTS/blob/dev/docs/source/models/xtts.md it should be OK.
但我看TTS的说明文档上面，是说支持中文的，奇了个怪了。

Please help me and have a look.
求助看看

```
Traceback (most recent call last):
  File "/home/admin/MyHeyGen/translate.py", line 22, in <module>
    translate(
  File "/home/admin/MyHeyGen/translate.py", line 12, in translate
    engine(video_filename, output_filename)
  File "/home/admin/MyHeyGen/core/engine.py", line 131, in __call__
    cloned_wav = cloner.process(
  File "/home/admin/MyHeyGen/core/voice_cloner.py", line 15, in process
    self.api.tts_to_file(
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/api.py", line 403, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/api.py", line 341, in tts
    wav = self.synthesizer.tts(
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 374, in tts
    outputs = self.tts_model.synthesize(
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 383, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 404, in inference_with_config
    return self.full_inference(text, ref_audio_path, language, **settings)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 468, in full_inference
    return self.inference(
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 500, in inference
    text_tokens = torch.IntTensor(self.tokenizer.encode(text, lang=language)).unsqueeze(0).to(self.device)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 585, in encode
    txt = self.preprocess_text(txt, lang)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 572, in preprocess_text
    txt = multilingual_cleaners(txt, lang)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 503, in multilingual_cleaners
    text = expand_abbreviations_multilingual(text, lang)
  File "/home/admin/MyHeyGen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'
```

**Comment by BrasD99** [comment]
@AIFSH check this [code](https://github.com/BrasD99/HeyGenClone/blob/main/core/mapper.py). I think it can fix this error!

**Comment by z-funfan** [comment]
> @AIFSH check this [code](https://github.com/BrasD99/HeyGenClone/blob/main/core/mapper.py). I think it can fix this error!

Thanks, I'll have a try

**Comment by AIFSH** [comment]
put your launch script maybe help! xtts v2 lang code for Chinese is 'zh-cn'
```
As of now, XTTS-v2 supports 16 languages: English (en), Spanish (es), French (fr), German (de), Italian (it), Portuguese (pt), Polish (pl), Turkish (tr), Russian (ru), Dutch (nl), Czech (cs), Arabic (ar), Chinese (zh-cn), Japanese (ja), Hungarian (hu) and Korean (ko).
```
https://tts.readthedocs.io/en/dev/models/xtts.html

**Comment by AIFSH** [comment]
```
pip uninstall TTS
pip install TTS==0.20.2
```
TTS 0.20.3 have bug

**Comment by z-funfan** [comment]
> ```
> pip uninstall TTS
> pip install TTS==0.20.2
> ```
> 
> TTS 0.20.3 have bug

That's true!

**Comment by weiraneve** [comment]
> pip install TTS==0.20.2

感觉作者大佬可以把这个放在sh文件或者提示出来嗷
