### ISSUE TITLE
'zh-cn' 语言参数不对？

### ISSUE THREAD

**Issue by LeXwDeX** [AIFSH/MyHeyGen#25]
我按照文档里的方式安装的TTS，会报错，说:`KeyError: 'zh-cn'`

翻看了 TTS的`_abbreviations`

```
DEFAULT_ALIGN_MODELS_HF = {
    'ja': 'jonatasgrosman/wav2vec2-large-xlsr-53-japanese',
    'zh': 'jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn',
    'nl': 'jonatasgrosman/wav2vec2-large-xlsr-53-dutch',
    'uk': 'Yehor/wav2vec2-xls-r-300m-uk-with-small-lm',
    'pt': 'jonatasgrosman/wav2vec2-large-xlsr-53-portuguese',
    'ar': 'jonatasgrosman/wav2vec2-large-xlsr-53-arabic',
    'cs': 'comodoro/wav2vec2-xls-r-300m-cs-250',
    'ru': 'jonatasgrosman/wav2vec2-large-xlsr-53-russian',
    'pl': 'jonatasgrosman/wav2vec2-large-xlsr-53-polish',
    'hu': 'jonatasgrosman/wav2vec2-large-xlsr-53-hungarian',
    'fi': 'jonatasgrosman/wav2vec2-large-xlsr-53-finnish',
    'fa': 'jonatasgrosman/wav2vec2-large-xlsr-53-persian',
    'el': 'jonatasgrosman/wav2vec2-large-xlsr-53-greek',
    'tr': 'mpoyraz/wav2vec2-xls-r-300m-cv7-turkish',
    'da': 'saattrupdan/wav2vec2-xls-r-300m-ftspeech',
    'he': 'imvladikon/wav2vec2-xls-r-300m-hebrew',
    'vi': 'nguyenvulebinh/wav2vec2-base-vi',
    'ko': 'kresnik/wav2vec2-large-xlsr-korean',
    'ur': 'kingabzpro/wav2vec2-large-xls-r-300m-Urdu',
    'te': 'anuragshas/wav2vec2-large-xlsr-53-telugu',
    'hi': 'theainerd/Wav2Vec2-large-xlsr-hindi'
}
```

看了官方文档，确实是 `zh-cn` 是正确入参。

```
You may need CTRL+C here!
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
TTS model tts_models/multilingual/multi-dataset/xtts_v2 Loaded
 I kept Israel safe.   en   zh
{
    "from": "en",
    "to": "zh",
    "trans_result": [
        {
            "src": "I kept Israel safe.",
            "dst": "我保护了以色列的安全。"
        }
    ]
}
You can edit it in config.json HUMAN_TRANS as 1 to enable human trans mode
final translate result:我保护了以色列的安全。
 > Text splitted to sentences.
['我保护了以色列的安全。']
Traceback (most recent call last):
  File "/data/py_myheygen/translate.py", line 22, in <module>
    translate(
  File "/data/py_myheygen/translate.py", line 12, in translate
    engine(video_filename, output_filename)
  File "/data/py_myheygen/core/engine.py", line 133, in __call__
    cloned_wav = cloner.process(
  File "/data/py_myheygen/core/voice_cloner.py", line 15, in process
    self.api.tts_to_file(
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/api.py", line 403, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/api.py", line 341, in tts
    wav = self.synthesizer.tts(
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 374, in tts
    outputs = self.tts_model.synthesize(
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 413, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 435, in inference_with_config
    return self.full_inference(text, ref_audio_path, language, **settings)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 504, in full_inference
    return self.inference(
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 536, in inference
    text_tokens = torch.IntTensor(self.tokenizer.encode(text, lang=language)).unsqueeze(0).to(self.device)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 588, in encode
    txt = self.preprocess_text(txt, lang)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 575, in preprocess_text
    txt = multilingual_cleaners(txt, lang)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 503, in multilingual_cleaners
    text = expand_abbreviations_multilingual(text, lang)
  File "/data/py_myheygen/venv/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'

```

```
_abbreviations = {
    "en": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("mrs", "misess"),
            ("mr", "mister"),
            ("dr", "doctor"),
            ("st", "saint"),
            ("co", "company"),
            ("jr", "junior"),
            ("maj", "major"),
            ("gen", "general"),
            ("drs", "doctors"),
            ("rev", "reverend"),
            ("lt", "lieutenant"),
            ("hon", "honorable"),
            ("sgt", "sergeant"),
            ("capt", "captain"),
            ("esq", "esquire"),
            ("ltd", "limited"),
            ("col", "colonel"),
            ("ft", "fort"),
        ]
    ],
    "es": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("sra", "señora"),
            ("sr", "señor"),
            ("dr", "doctor"),
            ("dra", "doctora"),
            ("st", "santo"),
            ("co", "compañía"),
            ("jr", "junior"),
            ("ltd", "limitada"),
        ]
    ],
    "fr": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("mme", "madame"),
            ("mr", "monsieur"),
            ("dr", "docteur"),
            ("st", "saint"),
            ("co", "compagnie"),
            ("jr", "junior"),
            ("ltd", "limitée"),
        ]
    ],
    "de": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("fr", "frau"),
            ("dr", "doktor"),
            ("st", "sankt"),
            ("co", "firma"),
            ("jr", "junior"),
        ]
    ],
    "pt": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("sra", "senhora"),
            ("sr", "senhor"),
            ("dr", "doutor"),
            ("dra", "doutora"),
            ("st", "santo"),
            ("co", "companhia"),
            ("jr", "júnior"),
            ("ltd", "limitada"),
        ]
    ],
    "it": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            # ("sig.ra", "signora"),
            ("sig", "signore"),
            ("dr", "dottore"),
            ("st", "santo"),
            ("co", "compagnia"),
            ("jr", "junior"),
            ("ltd", "limitata"),
        ]
    ],
    "pl": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("p", "pani"),
            ("m", "pan"),
            ("dr", "doktor"),
            ("sw", "święty"),
            ("jr", "junior"),
        ]
    ],
    "ar": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            # There are not many common abbreviations in Arabic as in English.
        ]
    ],
    "zh": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            # Chinese doesn't typically use abbreviations in the same way as Latin-based scripts.
        ]
    ],
    "cs": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("dr", "doktor"),  # doctor
            ("ing", "inženýr"),  # engineer
            ("p", "pan"),  # Could also map to pani for woman but no easy way to do it
            # Other abbreviations would be specialized and not as common.
        ]
    ],
    "ru": [
        (re.compile("\\b%s\\b" % x[0], re.IGNORECASE), x[1])
        for x in [
            ("г-жа", "госпожа"),  # Mrs.
            ("г-н", "господин"),  # Mr.
            ("д-р", "доктор"),  # doctor
            # Other abbreviations are less common or specialized.
        ]
    ],
    "nl": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("dhr", "de heer"),  # Mr.
            ("mevr", "mevrouw"),  # Mrs.
            ("dr", "dokter"),  # doctor
            ("jhr", "jonkheer"),  # young lord or nobleman
            # Dutch uses more abbreviations, but these are the most common ones.
        ]
    ],
    "tr": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("b", "bay"),  # Mr.
            ("byk", "büyük"),  # büyük
            ("dr", "doktor"),  # doctor
            # Add other Turkish abbreviations here if needed.
        ]
    ],
    "hu": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            ("dr", "doktor"),  # doctor
            ("b", "bácsi"),  # Mr.
            ("nőv", "nővér"),  # nurse
            # Add other Hungarian abbreviations here if needed.
        ]
    ],
    "ko": [
        (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
        for x in [
            # Korean doesn't typically use abbreviations in the same way as Latin-based scripts.
        ]
    ],
}
```

报错是字典里找不到key，手工添加了代码到源包文件的字典后面，临时跑了下，没报错了。

```
_abbreviations["zh-cn"] = _abbreviations["zh"]
_symbols_multilingual["zh-cn"] = _symbols_multilingual["zh"]
```

**Comment by LeXwDeX** [comment]
哎呀，跑起来问题挺多的。
后面再来看看了。
