### ISSUE TITLE
提示initialization of _pywrap_checkpoint_reader raised unreported exception

### ISSUE THREAD

**Issue by faiejir** [AIFSH/MyHeyGen#32]
module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1186, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
initialization of _pywrap_checkpoint_reader raised unreported exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MyHeyGen/translate.py", line 4, in <module>
    from core.engine import Engine
  File "/root/MyHeyGen/core/engine.py", line 2, in <module>
    from core.voice_cloner import VoiceCloner
  File "/root/MyHeyGen/core/voice_cloner.py", line 29, in <module>
    from TTS.tts.configs.xtts_config import XttsConfig
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/TTS/tts/configs/xtts_config.py", line 5, in <module>
    from TTS.tts.models.xtts import XttsArgs, XttsAudioConfig
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 10, in <module>
    from TTS.tts.layers.xtts.gpt import GPT
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/TTS/tts/layers/xtts/gpt.py", line 12, in <module>
    from TTS.tts.layers.xtts.gpt_inference import GPT2InferenceModel
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/TTS/tts/layers/xtts/gpt_inference.py", line 5, in <module>
    from transformers import GPT2PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1175, in __getattr__
    value = getattr(module, name)
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1174, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/heygen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1186, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
initialization of _pywrap_checkpoint_reader raised unreported exception

**Comment by AIFSH** [comment]
make sure your transfermers version right
