### ISSUE TITLE
TypeError: Descriptors cannot be created directly

### ISSUE THREAD

**Issue by yamendei** [AIFSH/MyHeyGen#34]
python translate.py /root/MyHeyGen/test/src.mp4 'zh-cn' -o /root/MyHeyGen/test/out_zh.mp4
Traceback (most recent call last):
  File "C:\AI\MyHeyGen\translate.py", line 4, in <module>
    from core.engine import Engine
  File "C:\AI\MyHeyGen\core\engine.py", line 4, in <module>
    from core.scene_preprocessor import ScenePreprocessor
  File "C:\AI\MyHeyGen\core\scene_preprocessor.py", line 9, in <module>
    from deepface import DeepFace
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\DeepFace.py", line 14, in <module>
    import tensorflow as tf
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by AIFSH** [comment]
just follow the note
