### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by levicn** [AIFSH/MyHeyGen#39]
```
Using CodeFormer upscale video, creating output!!!
/export/apps/MyHeyGen/test/out_zh.mp4: No such file or directory
Traceback (most recent call last):
  File "/export/apps/MyHeyGen/CodeFormer/inference_codeformer.py", line 93, in <module>
    vidreader = VideoReader(args.input_path)
  File "/export/apps/MyHeyGen/CodeFormer/basicsr/utils/video_util.py", line 43, in __init__
    meta = get_video_meta_info(video_path)
  File "/export/apps/MyHeyGen/CodeFormer/basicsr/utils/video_util.py", line 19, in get_video_meta_info
    probe = ffmpeg.probe(video_path)
  File "/root/miniconda3/envs/myheygen/lib/python3.10/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
```

已经到了最后一步了（bgm.wav,video_extend.mp4,voice_cloned.wav,zimu.txt已经生成了），
然后提示输出文件不存在，很奇怪，这个输出文件不应该是程序来创建吗？
如果我把源文件拷贝一份，命名成out_zh.mp4是可以过的，但是生成的结果不对，还是原语言。
感觉遇到这个问题的不少，怎么解呢？

**Comment by AIFSH** [comment]
Absolute path! readme detail please!

**Comment by levicn** [comment]
Traceback (most recent call last):
  File "/root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/myheygen/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/export/apps/MyHeyGen/video-retalking/inference.py", line 16, in <module>
    from third_part.GPEN.gpen_face_enhancer import FaceEnhancement
  File "/export/apps/MyHeyGen/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 8, in <module>
    from face_model.face_gan import FaceGAN
  File "/export/apps/MyHeyGen/video-retalking/third_part/GPEN/face_model/face_gan.py", line 13, in <module>
    from face_model.gpen_model import FullGenerator
  File "/export/apps/MyHeyGen/video-retalking/third_part/GPEN/face_model/gpen_model.py", line 16, in <module>
    from face_model.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/export/apps/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/export/apps/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_act.py", line 13, in <module>
    fused = load(
  File "/root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /root/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /export/apps/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/TH -isystem /root/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/include/THC -isystem /root/miniconda3/envs/myheygen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /export/apps/MyHeyGen/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
ninja: build stopped: subcommand failed.

使用的就是绝对路径，前面还有一个错误信息，根本原因应该是CUDA的版本不对，导致 out_zh.mp4没有输出。
Readme 可以写一下最小支持的 CUDA 版本。

**Comment by levicn** [comment]
已经跑通了，附一个更新 CUDA 版本的教程：
https://zhuanlan.zhihu.com/p/520536351
