### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by fengyunzaidushi** [AIFSH/MyHeyGen#4]
step 6 occur this mistake:
```

[Step 6] Lip Synthesis::   0%|                                                                                        | 0/27 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/inference.py", line 367, in <module>
    main()
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/inference.py", line 258, in main
    restorer = GFPGANer(model_path='checkpoints/GFPGANv1.4.pth', upscale=1, arch='clean', \
  File "/mnt/sda/github/11yue/MyHeyGen/video-retalking/third_part/GFPGAN/gfpgan/utils.py", line 76, in __init__
    self.face_helper = FaceRestoreHelper(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 99, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=self.device, model_rootpath=model_rootpath)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/facexlib/detection/__init__.py", line 18, in init_detection_model
    model_path = load_file_from_url(
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/facexlib/utils/misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/miniconda3/envs/myheygen/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

**Comment by fengyunzaidushi** [comment]
这是网络错误。
